### ISSUE TITLE
Preliminary code review

### ISSUE THREAD

**Issue by nrvale0** [Nextdoor/rightscale_rightlink10_rightscripts#5]
Requesting a preliminary code review now that docstrings have been finished.

** NOTE ** : The code is *not* feature complete. The intent is for a *high-level* review in terms of coding standards and/or general design smell.

@diranged @siminm

**Comment by diranged** [comment]
https://github.com/Nextdoor/rightscale_rightlink10_rightscripts/blob/master/tasks.py#L67-L70:
There is some pretty ugly formatting going on here. Check in with @siminm  on the proper style-guide-approved way to handle this.

https://github.com/Nextdoor/rightscale_rightlink10_rightscripts/blob/master/nextdoor/metadata.rb#L14:
Lets re-organize the inputs so they are alphabetical. Since the inputs can be used by many different scripts, there is no real good way to organize them on a per-usage basis.

https://github.com/Nextdoor/rightscale_rightlink10_rightscripts/blob/master/nextdoor/metadata.rb#L126:
Rename `DEFAULT_DOMAIN` to `DOMAIN` -- as there is no real concept of a second domain name for the host (other than search order).

https://github.com/Nextdoor/rightscale_rightlink10_rightscripts/blob/master/nextdoor/metadata.rb#L171:
Reformat all long strings (over 80char) so that they are multi line. Side-scrolling sucks. :)

https://github.com/Nextdoor/rightscale_rightlink10_rightscripts/blob/master/nextdoor/mounts.py:
Lets re-facter this to use my new storage-scripts code.The system is simpler. You could try bringing that module into this as a submodule and see if RightScale recursively pulls submodules -- that would be nifty.

https://github.com/Nextdoor/rightscale_rightlink10_rightscripts/blob/master/nextdoor/lib/kingpin/kingpin.zip:
I get why we're doing this -- but it kind of sucks. Lets at least version the zip so that we know exactly what SHA1 it was built with. (Also, I suggest updating to our latest `pre_release` kingpin zip)

https://github.com/Nextdoor/rightscale_rightlink10_rightscripts/blob/master/nextdoor/hostname.py#L82:
Why is `htop` a dependency here?

https://github.com/Nextdoor/rightscale_rightlink10_rightscripts/blob/master/nextdoor/hostname.py#L34:
You are nly doing a few of the checks we had in our old code -- there is some work to do here to make sure that the total FQDN isn't too long, the hostname isnt too long, and that if the hostname IS too long, that we ensure the instance-ID is not clobbered.

https://github.com/Nextdoor/rightscale_rightlink10_rightscripts/blob/master/nextdoor/puppet-install.py#L43:
Doing an apt-get update on every script invocation is going to be really slow (30-60 seconds per) ... can we just move this into its own startup script and have it run first?

https://github.com/Nextdoor/rightscale_rightlink10_rightscripts/blob/master/nextdoor/puppet-install.py#L67:
1) Line length ..
2) Can you use a shorter file name? :)

https://github.com/Nextdoor/rightscale_rightlink10_rightscripts/blob/master/nextdoor/puppet-install.py#L88:
Not sure why you're doing the if statement here? Lets talk in person about this.

https://github.com/Nextdoor/rightscale_rightlink10_rightscripts/blob/master/nextdoor/puppet-install.py#L121:
Not pythonic -- look at the style guide.

https://github.com/Nextdoor/rightscale_rightlink10_rightscripts/blob/master/nextdoor/puppet-install.py#L126:
style guide... we don't use the `.format()` commadn typically. We use the `"foo bar %s" % (var)` mechanism.
